# Camera parameters based on YCBV dataset camera parameters
image_width: 960
image_height: 540
camera_name: "webcam"
camera_matrix:
  rows: 3
  cols: 3
  data: [616.655, 0.0, 320.154, 0.0, 616.760, 239.480, 0.0, 0.0, 1.0]
distortion_model: "plumb_bob"
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.0, 0.0, 0.0, 0.0, 0.0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
projection_matrix:
  rows: 3
  cols: 4
  data: [616.655, 0.0, 320.154, 0.0, 0.0, 616.760, 239.480, 0.0, 0.0, 0.0, 1.0, 0.0]
