/**:
  ros__parameters:
    device: cpu
    pose_estimator_type: cosypose

    renderer:
      renderer_type: panda3d
      n_workers: 8
      gpu_renderer: False

    cosypose:
      dataset_name: ycbv
      inference:
        n_refiner_iterations: 1
        n_coarse_iterations: 1
        detection_th: 0.9
        mask_th: 0.8
        # labels_to_keep:
        #   - "ycbv-obj_000014"

    cameras:
      timeout: 0.0
      min_num: 1
      names: ["cam_1"]
      cam_1:
        compressed: false
        image_topic: /image_raw
        info_topic: /camera_info
