name: 'Humble: Build and Test'
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - '*'
jobs:
  test_happypose_ros:
    runs-on: ubuntu-22.04
    env:
      HAPPYPOSE_DATA_DIR: /tmp/local_data
    steps:
      - name: Install EGL mesa - required for Panda3D renderer
        run: |
          sudo apt-get update
          sudo apt-get install -qqy libegl1-mesa libegl1-mesa-dev
      - name: Install Python C headers and remove Blinker version conflicting with HappyPose
        run: |
          sudo apt-get update
          sudo apt-get install -qqy python3-dev
          sudo apt purge -qqy python3-blinker
      - name: Caching of the HappyPose installation and data
        uses: actions/cache@v4
        with:
          path: /tmp/local_data
          key: data
      - name: Update pip
        run: pip install -U pip
      - name: Download HappyPose source
        working-directory: /tmp
        run: |
          git clone --branch dev --recurse-submodules https://github.com/agimus-project/happypose.git
      - name: Build and install HappyPose
        working-directory: /tmp/happypose
        run: pip install -r requirements/pypi.txt -r requirements/cpu.txt
      - name: Download pre-trained models required for tests
        run: |
          mkdir -p /tmp/local_data
          python -m happypose.toolbox.utils.download \
            --bop_dataset ycbv \
            --cosypose_models  \
              detector-bop-ycbv-pbr--970850 \
              coarse-bop-ycbv-pbr--724183 \
              refiner-bop-ycbv-pbr--604090
      - name: Unzip HappyPose YCBV models
        working-directory: /tmp/local_data/bop_datasets/ycbv
        run: |
          unzip -n -qq ycbv_base.zip
          unzip -n -qq ycbv_models.zip
      - name: Remove incompatible PyTest version
        run: pip uninstall -y pytest
      - name: Install ROS 2 Humble
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - name: Build and test happypose_ros
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: happypose_ros
          target-ros2-distro: humble
